### ISSUE TITLE
 Invalid now...

### ISSUE THREAD

**Issue by Apoclypt1c** [zirawell/R-Store#2]
https://github.com/zirawell/R-Store/blame/2c3a21df60b2f9d200368b10c0f9bf5a355766d8/Rule/QuanX/Adblock/App/E/%E9%A5%BF%E4%BA%86%E4%B9%88/rewrite/eleme.conf

Eleme script can't block the start screen spalsh ads, but at the same time it can block all historical orders.😂😂

I don't know if it only works like this on me or not. Please check it out. Thanks!

**Comment by zirawell** [comment]
> https://github.com/zirawell/R-Store/blame/2c3a21df60b2f9d200368b10c0f9bf5a355766d8/Rule/QuanX/Adblock/App/E/%E9%A5%BF%E4%BA%86%E4%B9%88/rewrite/eleme.conf
> 
> Eleme script can't block the start screen spalsh ads, but at the same time it can block all historical orders.😂😂
> 
> I don't know if it only works like this on me or not. Please check it out. Thanks!

It still works fine for me with the latest version. Please check if there is another rule works conflict with it.
